site_name: '👋 {{cookiecutter.project_name}}'
theme:
  name: material
  theme:
  palette:
    primary: indigo
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - '{{cookiecutter.pkg_name}}'
  - docs
